[package]
name = "mpc-aes128-cbc-client-io"
version = "0.1.0"
edition = "2021"

[dependencies]
stoffel = { package = "stoffel-rust-sdk", version = "=0.1.3", path = "../../../stoffel-rust-sdk" }
tokio = { version = "=1.52.3", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
stoffel-bindgen = { version = "=0.1.3", path = "../../../stoffel-bindgen" }
