[net]
git-fetch-with-cli = true

[patch."https://github.com/Stoffel-Labs/stoffel-mpc-coordinator.git"]
stoffel-mpc-coordinator = { path = "../stoffel-mpc-coordinator" }

[patch."https://github.com/Stoffel-Labs/stoffel-networking.git"]
stoffelnet = { path = "../stoffel-network" }
