// This file is generated by stoffel::generate_bindings. Regenerate it after changing the program's ClientStore IO.

pub struct ProgramManifest;
impl stoffel::GeneratedProgramManifest for ProgramManifest {
    const BACKEND: stoffel::MpcBackend = stoffel::MpcBackend::HoneyBadger;

    fn client_input_types(client_slot: u64) -> Option<&'static [stoffel::ClientValueType]> {
        match client_slot {
            _ => None,
        }
    }

    fn client_output_types(client_slot: u64) -> Option<&'static [stoffel::ClientValueType]> {
        match client_slot {
            _ => None,
        }
    }
}

// The default program does not declare ClientStore IO.
