//! Build-script helpers for generating typed client IO bindings from `.stflb`.

use std::fmt::Write as _;
use std::path::Path;

use stoffel_vm_types::compiled_binary::{MpcBackend, MpcCurve};
use stoffel_vm_types::core_types::ShareType;

use crate::error::{Error, Result};
use crate::program::Program;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BindingsConfig {
    pub crate_path: String,
    pub derives: Vec<String>,
}

impl Default for BindingsConfig {
    fn default() -> Self {
        Self {
            crate_path: "stoffel".to_owned(),
            derives: vec![
                "Debug".to_owned(),
                "Clone".to_owned(),
                "PartialEq".to_owned(),
            ],
        }
    }
}

/// Generate Rust client IO bindings from a compiled `.stflb` file.
///
/// This is intended for application `build.rs` files:
///
/// ```no_run
/// # fn main() -> Result<(), Box<dyn std::error::Error>> {
/// let out_dir = std::env::var("OUT_DIR")?;
/// stoffel::generate_bindings(
///     "program.stflb",
///     format!("{out_dir}/stoffel_bindings.rs"),
/// )?;
/// # Ok(())
/// # }
/// ```
pub fn generate_bindings(
    bytecode_path: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
) -> Result<()> {
    generate_bindings_with_config(bytecode_path, out_file, BindingsConfig::default())
}

/// Generate Rust client IO bindings from a compiled `.stflb` file with custom
/// crate path or derives.
pub fn generate_bindings_with_config(
    bytecode_path: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
    config: BindingsConfig,
) -> Result<()> {
    let program = Program::from_bytecode_file(bytecode_path)?;
    let source = generate_bindings_source(&program, &config)?;
    std::fs::write(out_file, source)?;
    Ok(())
}

pub(crate) fn generate_bindings_source(
    program: &Program,
    config: &BindingsConfig,
) -> Result<String> {
    let mut source = String::new();
    writeln!(
        source,
        "// This file is generated by stoffel::generate_bindings. Do not edit by hand."
    )
    .expect("writing to String cannot fail");
    writeln!(source).expect("writing to String cannot fail");

    emit_program_manifest(&mut source, program, &config.crate_path)?;
    writeln!(source).expect("writing to String cannot fail");

    if !program.has_client_io() {
        writeln!(source, "// The program does not declare ClientStore IO.").expect("infallible");
        return Ok(source);
    }

    for client in program.clients() {
        let slot = client.client_slot();
        emit_payload(
            &mut source,
            &config.crate_path,
            &config.derives,
            &format!("Client{slot}Inputs"),
            "input",
            client.inputs(),
            true,
        )?;
        writeln!(source).expect("writing to String cannot fail");
        emit_payload(
            &mut source,
            &config.crate_path,
            &config.derives,
            &format!("Client{slot}Outputs"),
            "output",
            client.outputs(),
            false,
        )?;
        writeln!(source).expect("writing to String cannot fail");
    }

    Ok(source)
}

fn emit_program_manifest(source: &mut String, program: &Program, crate_path: &str) -> Result<()> {
    writeln!(source, "pub struct ProgramManifest;").expect("writing to String cannot fail");
    writeln!(
        source,
        "impl {crate_path}::GeneratedProgramManifest for ProgramManifest {{"
    )
    .expect("writing to String cannot fail");
    writeln!(
        source,
        "    const BACKEND: {crate_path}::MpcBackend = {};",
        sdk_backend_expr(
            crate_path,
            program.bytecode_backend(),
            program.bytecode_curve()
        )
    )
    .expect("writing to String cannot fail");
    writeln!(
        source,
        "    fn client_input_types(client_slot: u64) -> Option<&'static [{crate_path}::ClientValueType]> {{"
    )
    .expect("writing to String cannot fail");
    writeln!(source, "        match client_slot {{").expect("writing to String cannot fail");
    for client in program.clients() {
        writeln!(
            source,
            "            {} => Some(&{}),",
            client.client_slot(),
            client_value_type_array(crate_path, client.inputs())?
        )
        .expect("writing to String cannot fail");
    }
    writeln!(source, "            _ => None,").expect("writing to String cannot fail");
    writeln!(source, "        }}").expect("writing to String cannot fail");
    writeln!(source, "    }}").expect("writing to String cannot fail");

    writeln!(
        source,
        "    fn client_output_types(client_slot: u64) -> Option<&'static [{crate_path}::ClientValueType]> {{"
    )
    .expect("writing to String cannot fail");
    writeln!(source, "        match client_slot {{").expect("writing to String cannot fail");
    for client in program.clients() {
        writeln!(
            source,
            "            {} => Some(&{}),",
            client.client_slot(),
            client_value_type_array(crate_path, client.outputs())?
        )
        .expect("writing to String cannot fail");
    }
    writeln!(source, "            _ => None,").expect("writing to String cannot fail");
    writeln!(source, "        }}").expect("writing to String cannot fail");
    writeln!(source, "    }}").expect("writing to String cannot fail");
    writeln!(source, "}}").expect("writing to String cannot fail");
    Ok(())
}

fn sdk_backend_expr(crate_path: &str, backend: MpcBackend, curve: MpcCurve) -> String {
    match backend {
        MpcBackend::HoneyBadger => format!("{crate_path}::MpcBackend::HoneyBadger"),
        MpcBackend::Avss => format!(
            "{crate_path}::MpcBackend::Avss {{ curve: {} }}",
            sdk_curve_expr(crate_path, curve)
        ),
    }
}

fn sdk_curve_expr(crate_path: &str, curve: MpcCurve) -> String {
    let variant = match curve {
        MpcCurve::Bls12_381 => "Bls12_381",
        MpcCurve::Bn254 => "Bn254",
        MpcCurve::Curve25519 => "Curve25519",
        MpcCurve::Ed25519 => "Ed25519",
    };
    format!("{crate_path}::Curve::{variant}")
}

fn client_value_type_array(crate_path: &str, share_types: &[ShareType]) -> Result<String> {
    let mut values = String::from("[");
    for (index, share_type) in share_types.iter().enumerate() {
        if index > 0 {
            values.push_str(", ");
        }
        write!(
            values,
            "{crate_path}::ClientValueType::{}",
            client_value_type_variant(*share_type)?
        )
        .expect("writing to String cannot fail");
    }
    values.push(']');
    Ok(values)
}

fn emit_payload(
    source: &mut String,
    crate_path: &str,
    derives: &[String],
    struct_name: &str,
    field_prefix: &str,
    share_types: &[ShareType],
    is_input: bool,
) -> Result<()> {
    if !derives.is_empty() {
        writeln!(source, "#[derive({})]", derives.join(", "))
            .expect("writing to String cannot fail");
    }
    writeln!(source, "pub struct {struct_name} {{").expect("writing to String cannot fail");
    for (ordinal, share_type) in share_types.iter().enumerate() {
        writeln!(
            source,
            "    pub {field_prefix}_{ordinal}: {},",
            rust_type(*share_type)?
        )
        .expect("writing to String cannot fail");
    }
    writeln!(source, "}}").expect("writing to String cannot fail");

    if is_input {
        emit_inputs_impl(source, crate_path, struct_name, field_prefix, share_types)
    } else {
        emit_outputs_impl(source, crate_path, struct_name, field_prefix, share_types)
    }
}

fn emit_inputs_impl(
    source: &mut String,
    crate_path: &str,
    struct_name: &str,
    field_prefix: &str,
    share_types: &[ShareType],
) -> Result<()> {
    writeln!(
        source,
        "impl {crate_path}::TypedClientInputs for {struct_name} {{"
    )
    .expect("writing to String cannot fail");
    writeln!(
        source,
        "    fn into_values(self) -> Vec<{crate_path}::Value> {{"
    )
    .expect("writing to String cannot fail");
    writeln!(source, "        vec![").expect("writing to String cannot fail");
    for ordinal in 0..share_types.len() {
        writeln!(
            source,
            "            {crate_path}::Value::from(self.{field_prefix}_{ordinal}),"
        )
        .expect("writing to String cannot fail");
    }
    writeln!(source, "        ]").expect("writing to String cannot fail");
    writeln!(source, "    }}").expect("writing to String cannot fail");
    emit_value_types(source, crate_path, share_types)?;
    writeln!(source, "}}").expect("writing to String cannot fail");
    Ok(())
}

fn emit_outputs_impl(
    source: &mut String,
    crate_path: &str,
    struct_name: &str,
    field_prefix: &str,
    share_types: &[ShareType],
) -> Result<()> {
    writeln!(
        source,
        "impl {crate_path}::TypedClientOutputs for {struct_name} {{"
    )
    .expect("writing to String cannot fail");
    writeln!(
        source,
        "    fn from_values(values: Vec<{crate_path}::Value>) -> {crate_path}::Result<Self> {{"
    )
    .expect("writing to String cannot fail");
    writeln!(source, "        let expected = Self::value_types().len();")
        .expect("writing to String cannot fail");
    writeln!(source, "        let actual = values.len();").expect("writing to String cannot fail");
    writeln!(source, "        if actual != expected {{").expect("writing to String cannot fail");
    writeln!(
        source,
        "            return Err({crate_path}::Error::InvalidInput(format!(\"expected {{expected}} typed outputs, got {{actual}}\")));"
    )
    .expect("writing to String cannot fail");
    writeln!(source, "        }}").expect("writing to String cannot fail");
    writeln!(source, "        let mut values = values.into_iter();")
        .expect("writing to String cannot fail");
    writeln!(source, "        Ok(Self {{").expect("writing to String cannot fail");
    for (ordinal, share_type) in share_types.iter().enumerate() {
        writeln!(
            source,
            "            {field_prefix}_{ordinal}: <{} as {crate_path}::ClientOutputValue>::try_from_sdk_value(values.next().expect(\"length checked\"))?,",
            rust_type(*share_type)?
        )
        .expect("writing to String cannot fail");
    }
    writeln!(source, "        }})").expect("writing to String cannot fail");
    writeln!(source, "    }}").expect("writing to String cannot fail");
    emit_value_types(source, crate_path, share_types)?;
    writeln!(source, "}}").expect("writing to String cannot fail");
    Ok(())
}

fn emit_value_types(
    source: &mut String,
    crate_path: &str,
    share_types: &[ShareType],
) -> Result<()> {
    writeln!(
        source,
        "    fn value_types() -> Vec<{crate_path}::ClientValueType> {{"
    )
    .expect("writing to String cannot fail");
    writeln!(source, "        vec![").expect("writing to String cannot fail");
    for share_type in share_types {
        writeln!(
            source,
            "            {crate_path}::ClientValueType::{},",
            client_value_type_variant(*share_type)?
        )
        .expect("writing to String cannot fail");
    }
    writeln!(source, "        ]").expect("writing to String cannot fail");
    writeln!(source, "    }}").expect("writing to String cannot fail");
    Ok(())
}

fn rust_type(share_type: ShareType) -> Result<&'static str> {
    match share_type {
        ShareType::SecretInt { bit_length: 1 } => Ok("bool"),
        ShareType::SecretInt { bit_length } if bit_length > 1 => Ok("i64"),
        ShareType::SecretFixedPoint { .. } => Ok("f64"),
        ShareType::SecretInt { bit_length } => Err(Error::Unsupported(format!(
            "cannot generate Rust binding for secret integer bit length {bit_length}"
        ))),
    }
}

fn client_value_type_variant(share_type: ShareType) -> Result<&'static str> {
    match share_type {
        ShareType::SecretInt { bit_length: 1 } => Ok("Boolean"),
        ShareType::SecretInt { bit_length } if bit_length > 1 => Ok("Integer"),
        ShareType::SecretFixedPoint { .. } => Ok("FixedPoint"),
        ShareType::SecretInt { bit_length } => Err(Error::Unsupported(format!(
            "cannot generate Rust binding for secret integer bit length {bit_length}"
        ))),
    }
}
