// This file is generated by stoffel::generate_bindings. Do not edit by hand.

pub struct ProgramManifest;
impl stoffel::GeneratedProgramManifest for ProgramManifest {
    const BACKEND: stoffel::MpcBackend = stoffel::MpcBackend::HoneyBadger;
    fn client_input_types(client_slot: u64) -> Option<&'static [stoffel::ClientValueType]> {
        match client_slot {
            0 => Some(&[
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
            ]),
            _ => None,
        }
    }
    fn client_output_types(client_slot: u64) -> Option<&'static [stoffel::ClientValueType]> {
        match client_slot {
            0 => Some(&[
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
                stoffel::ClientValueType::FixedPoint,
            ]),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Client0Inputs {
    pub input_0: f64,
    pub input_1: f64,
    pub input_2: f64,
    pub input_3: f64,
    pub input_4: f64,
    pub input_5: f64,
}
impl stoffel::TypedClientInputs for Client0Inputs {
    fn into_values(self) -> Vec<stoffel::Value> {
        vec![
            stoffel::Value::from(self.input_0),
            stoffel::Value::from(self.input_1),
            stoffel::Value::from(self.input_2),
            stoffel::Value::from(self.input_3),
            stoffel::Value::from(self.input_4),
            stoffel::Value::from(self.input_5),
        ]
    }
    fn value_types() -> Vec<stoffel::ClientValueType> {
        vec![
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
        ]
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Client0Outputs {
    pub output_0: f64,
    pub output_1: f64,
    pub output_2: f64,
    pub output_3: f64,
    pub output_4: f64,
    pub output_5: f64,
}
impl stoffel::TypedClientOutputs for Client0Outputs {
    fn from_values(values: Vec<stoffel::Value>) -> stoffel::Result<Self> {
        let expected = Self::value_types().len();
        let actual = values.len();
        if actual != expected {
            return Err(stoffel::Error::InvalidInput(format!(
                "expected {expected} typed outputs, got {actual}"
            )));
        }
        let mut values = values.into_iter();
        Ok(Self {
            output_0: <f64 as stoffel::ClientOutputValue>::try_from_sdk_value(
                values.next().expect("length checked"),
            )?,
            output_1: <f64 as stoffel::ClientOutputValue>::try_from_sdk_value(
                values.next().expect("length checked"),
            )?,
            output_2: <f64 as stoffel::ClientOutputValue>::try_from_sdk_value(
                values.next().expect("length checked"),
            )?,
            output_3: <f64 as stoffel::ClientOutputValue>::try_from_sdk_value(
                values.next().expect("length checked"),
            )?,
            output_4: <f64 as stoffel::ClientOutputValue>::try_from_sdk_value(
                values.next().expect("length checked"),
            )?,
            output_5: <f64 as stoffel::ClientOutputValue>::try_from_sdk_value(
                values.next().expect("length checked"),
            )?,
        })
    }
    fn value_types() -> Vec<stoffel::ClientValueType> {
        vec![
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
            stoffel::ClientValueType::FixedPoint,
        ]
    }
}
